# Generated by Django 5.0.14 on 2025-07-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('jiti', 'Jiti'), ('sungura', 'Sungura'), ('jazz', 'Jazz'), ('hip_hop', 'Hip-Hop'), ('gospel', 'Gospel'), ('reggae', 'Reggae'), ('zimdancehall', 'Zimdancehall'), ('mbira', 'Mbira'), ('dancehall', 'Dancehall'), ('trap', 'Trap')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque_type', models.CharField(choices=[('thank_you', 'Thank You'), ('wood', 'Wood'), ('ruby', 'Ruby'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('emerald', 'Emerald')], default='thank_you', max_length=10)),
                ('hash_key', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(upload_to='albums/covers/')),
                ('description', models.TextField()),
                ('track_count', models.PositiveIntegerField(default=0)),
                ('copyright_info', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.TextField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.genre')),
            ],
        ),
        migrations.CreateModel(
            name='PlaquePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('album_supported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaque_purchases', to='albums.album')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('plaque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_details', to='albums.plaque')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bid_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZWL', 'ZWL')], max_length=3)),
                ('plaque_count', models.PositiveBigIntegerField(default=0)),
                ('amount_supported', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='albums.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('featured_artists', models.CharField(blank=True, max_length=255, null=True)),
                ('track_art', models.ImageField(blank=True, null=True, upload_to='albums/tracks/art/')),
                ('track_credits', models.TextField(blank=True, null=True)),
                ('backing_vocals', models.CharField(blank=True, max_length=255, null=True)),
                ('instrumentation', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=255, null=True)),
                ('mastering_engineer', models.CharField(blank=True, max_length=255, null=True)),
                ('mixing_engineer', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='albums.album')),
            ],
            options={
                'ordering': ['track_number'],
                'unique_together': {('album', 'track_number')},
            },
        ),
    ]
