# Generated by Django 5.1.1 on 2024-09-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(upload_to='albums/covers/')),
                ('description', models.TextField()),
                ('track_count', models.IntegerField(blank=True, null=True)),
                ('copyright_info', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('credits', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('jiti', 'Jiti'), ('sungura', 'Sungura'), ('jazz', 'Jazz'), ('hip_hop', 'Hip-Hop'), ('gospel', 'Gospel'), ('reggae', 'Reggae'), ('zimdancehall', 'Zimdancehall'), ('mbira', 'Mbira'), ('dancehall', 'Dancehall'), ('trap', 'Trap')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque_type', models.CharField(choices=[('thank_you', 'Thank You'), ('wood', 'Wood'), ('ruby', 'Ruby'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('emerald', 'Emerald')], default='thank_you', max_length=10)),
                ('hash_key', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('audio_file', models.FileField(null=True, upload_to='albums/tracks/')),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('featured_artists', models.CharField(blank=True, max_length=255, null=True)),
                ('track_art', models.ImageField(blank=True, null=True, upload_to='albums/tracks/art/')),
                ('track_credits', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['track_number'],
            },
        ),
    ]
