# Generated by Django 5.1.1 on 2024-09-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaquePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('album_supported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaque_purchases', to='albums.album')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('plaque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_details', to='albums.plaque')),
            ],
        ),
    ]
