# Generated by Django 5.0.14 on 2025-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_track_credits_track_track_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='special_credits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
