# Generated by Django 5.0.14 on 2025-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_albumactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumactivity',
            name='plaque_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='albumactivity',
            name='usd_suport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='albumactivity',
            name='zwg_suport',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
