# Generated by Django 5.0.14 on 2025-05-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_albumactivity_plaque_count_albumactivity_usd_suport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumactivity',
            name='usd_suport',
        ),
        migrations.RemoveField(
            model_name='albumactivity',
            name='zwg_suport',
        ),
        migrations.AddField(
            model_name='albumactivity',
            name='amount_supported',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='albumactivity',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZWL', 'ZWL')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'track_number')},
        ),
    ]
