# Generated by Django 5.0.14 on 2025-05-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_remove_albumactivity_usd_suport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio_file',
        ),
    ]
